/**
 * This class is generated by jOOQ
 */
package org.example.jooq.db.public_.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jasuil implements Serializable {

	private static final long serialVersionUID = -753731018;

	private BigDecimal id;
	private String     name;

	public Jasuil() {}

	public Jasuil(Jasuil value) {
		this.id = value.id;
		this.name = value.name;
	}

	public Jasuil(
		BigDecimal id,
		String     name
	) {
		this.id = id;
		this.name = name;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Jasuil (");

		sb.append(id);
		sb.append(", ").append(name);

		sb.append(")");
		return sb.toString();
	}
}
