/**
 * This class is generated by jOOQ
 */
package org.example.jooq.db.public_.tables;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.example.jooq.db.public_.Public;
import org.example.jooq.db.public_.tables.records.JasuilRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jasuil extends TableImpl<JasuilRecord> {

	private static final long serialVersionUID = 203269312;

	/**
	 * The reference instance of <code>PUBLIC.JASUIL</code>
	 */
	public static final Jasuil JASUIL = new Jasuil();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<JasuilRecord> getRecordType() {
		return JasuilRecord.class;
	}

	/**
	 * The column <code>PUBLIC.JASUIL.ID</code>.
	 */
	public final TableField<JasuilRecord, BigDecimal> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL.precision(65535, 32767), this, "");

	/**
	 * The column <code>PUBLIC.JASUIL.NAME</code>.
	 */
	public final TableField<JasuilRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * Create a <code>PUBLIC.JASUIL</code> table reference
	 */
	public Jasuil() {
		this("JASUIL", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.JASUIL</code> table reference
	 */
	public Jasuil(String alias) {
		this(alias, JASUIL);
	}

	private Jasuil(String alias, Table<JasuilRecord> aliased) {
		this(alias, aliased, null);
	}

	private Jasuil(String alias, Table<JasuilRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Jasuil as(String alias) {
		return new Jasuil(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Jasuil rename(String name) {
		return new Jasuil(name, null);
	}
}
