/**
 * This class is generated by jOOQ
 */
package org.example.jooq.db.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_4FF3E697_19EA_4D15_91FA_CCC0F22638A4</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_4FF3E697_19EA_4D15_91FA_CCC0F22638A4 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_4FF3E697_19EA_4D15_91FA_CCC0F22638A4", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_F2DF3874_4D5A_462E_BEBA_EB53431B4D2D</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_F2DF3874_4D5A_462E_BEBA_EB53431B4D2D = new SequenceImpl<Long>("SYSTEM_SEQUENCE_F2DF3874_4D5A_462E_BEBA_EB53431B4D2D", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
