/**
 * This class is generated by jOOQ
 */
package org.example.jooq.db.public_;


import javax.annotation.Generated;

import org.example.jooq.db.public_.tables.Jasuil;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.JASUIL
	 */
	public static final Jasuil JASUIL = org.example.jooq.db.public_.tables.Jasuil.JASUIL;
}
