/**
 * This class is generated by jOOQ
 */
package org.example.jooq.db.public_;


import javax.annotation.Generated;

import org.example.jooq.db.public_.tables.Comments;
import org.example.jooq.db.public_.tables.Posts;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.POSTS
	 */
	public static final Posts POSTS = org.example.jooq.db.public_.tables.Posts.POSTS;

	/**
	 * The table PUBLIC.COMMENTS
	 */
	public static final Comments COMMENTS = org.example.jooq.db.public_.tables.Comments.COMMENTS;
}
