/**
 * This class is generated by jOOQ
 */
package org.example.jooq.db.information_schema.tables.records;


import javax.annotation.Generated;

import org.example.jooq.db.information_schema.tables.Synonyms;
import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SynonymsRecord extends TableRecordImpl<SynonymsRecord> implements Record9<String, String, String, String, String, String, String, String, Integer> {

	private static final long serialVersionUID = 2039865566;

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_CATALOG</code>.
	 */
	public void setSynonymCatalog(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_CATALOG</code>.
	 */
	public String getSynonymCatalog() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_SCHEMA</code>.
	 */
	public void setSynonymSchema(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_SCHEMA</code>.
	 */
	public String getSynonymSchema() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_NAME</code>.
	 */
	public void setSynonymName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_NAME</code>.
	 */
	public String getSynonymName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_FOR</code>.
	 */
	public void setSynonymFor(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_FOR</code>.
	 */
	public String getSynonymFor() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_FOR_SCHEMA</code>.
	 */
	public void setSynonymForSchema(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SYNONYMS.SYNONYM_FOR_SCHEMA</code>.
	 */
	public String getSynonymForSchema() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SYNONYMS.TYPE_NAME</code>.
	 */
	public void setTypeName(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SYNONYMS.TYPE_NAME</code>.
	 */
	public String getTypeName() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SYNONYMS.STATUS</code>.
	 */
	public void setStatus(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SYNONYMS.STATUS</code>.
	 */
	public String getStatus() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SYNONYMS.REMARKS</code>.
	 */
	public void setRemarks(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SYNONYMS.REMARKS</code>.
	 */
	public String getRemarks() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SYNONYMS.ID</code>.
	 */
	public void setId(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SYNONYMS.ID</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, String, String, String, Integer> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, String, String, String, Integer> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Synonyms.SYNONYMS.SYNONYM_CATALOG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Synonyms.SYNONYMS.SYNONYM_SCHEMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Synonyms.SYNONYMS.SYNONYM_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Synonyms.SYNONYMS.SYNONYM_FOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Synonyms.SYNONYMS.SYNONYM_FOR_SCHEMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Synonyms.SYNONYMS.TYPE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Synonyms.SYNONYMS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Synonyms.SYNONYMS.REMARKS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Synonyms.SYNONYMS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getSynonymCatalog();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getSynonymSchema();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSynonymName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getSynonymFor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getSynonymForSchema();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getTypeName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getRemarks();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord value1(String value) {
		setSynonymCatalog(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord value2(String value) {
		setSynonymSchema(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord value3(String value) {
		setSynonymName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord value4(String value) {
		setSynonymFor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord value5(String value) {
		setSynonymForSchema(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord value6(String value) {
		setTypeName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord value7(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord value8(String value) {
		setRemarks(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord value9(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SynonymsRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Integer value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SynonymsRecord
	 */
	public SynonymsRecord() {
		super(Synonyms.SYNONYMS);
	}

	/**
	 * Create a detached, initialised SynonymsRecord
	 */
	public SynonymsRecord(String synonymCatalog, String synonymSchema, String synonymName, String synonymFor, String synonymForSchema, String typeName, String status, String remarks, Integer id) {
		super(Synonyms.SYNONYMS);

		setValue(0, synonymCatalog);
		setValue(1, synonymSchema);
		setValue(2, synonymName);
		setValue(3, synonymFor);
		setValue(4, synonymForSchema);
		setValue(5, typeName);
		setValue(6, status);
		setValue(7, remarks);
		setValue(8, id);
	}
}
