/**
 * This class is generated by jOOQ
 */
package org.example.jooq.db.information_schema;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.example.jooq.db.information_schema.tables.Catalogs;
import org.example.jooq.db.information_schema.tables.Collations;
import org.example.jooq.db.information_schema.tables.ColumnPrivileges;
import org.example.jooq.db.information_schema.tables.Columns;
import org.example.jooq.db.information_schema.tables.Constants;
import org.example.jooq.db.information_schema.tables.Constraints;
import org.example.jooq.db.information_schema.tables.CrossReferences;
import org.example.jooq.db.information_schema.tables.Domains;
import org.example.jooq.db.information_schema.tables.FunctionAliases;
import org.example.jooq.db.information_schema.tables.FunctionColumns;
import org.example.jooq.db.information_schema.tables.Help;
import org.example.jooq.db.information_schema.tables.InDoubt;
import org.example.jooq.db.information_schema.tables.Indexes;
import org.example.jooq.db.information_schema.tables.KeyColumnUsage;
import org.example.jooq.db.information_schema.tables.Locks;
import org.example.jooq.db.information_schema.tables.QueryStatistics;
import org.example.jooq.db.information_schema.tables.ReferentialConstraints;
import org.example.jooq.db.information_schema.tables.Rights;
import org.example.jooq.db.information_schema.tables.Roles;
import org.example.jooq.db.information_schema.tables.Schemata;
import org.example.jooq.db.information_schema.tables.Sequences;
import org.example.jooq.db.information_schema.tables.SessionState;
import org.example.jooq.db.information_schema.tables.Sessions;
import org.example.jooq.db.information_schema.tables.Settings;
import org.example.jooq.db.information_schema.tables.Synonyms;
import org.example.jooq.db.information_schema.tables.TableConstraints;
import org.example.jooq.db.information_schema.tables.TablePrivileges;
import org.example.jooq.db.information_schema.tables.TableTypes;
import org.example.jooq.db.information_schema.tables.Tables;
import org.example.jooq.db.information_schema.tables.Triggers;
import org.example.jooq.db.information_schema.tables.TypeInfo;
import org.example.jooq.db.information_schema.tables.Users;
import org.example.jooq.db.information_schema.tables.Views;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationSchema extends SchemaImpl {

	private static final long serialVersionUID = 1671425349;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA</code>
	 */
	public static final InformationSchema INFORMATION_SCHEMA = new InformationSchema();

	/**
	 * No further instances allowed
	 */
	private InformationSchema() {
		super("INFORMATION_SCHEMA");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			ReferentialConstraints.REFERENTIAL_CONSTRAINTS,
			KeyColumnUsage.KEY_COLUMN_USAGE,
			TableConstraints.TABLE_CONSTRAINTS,
			Synonyms.SYNONYMS,
			QueryStatistics.QUERY_STATISTICS,
			SessionState.SESSION_STATE,
			Locks.LOCKS,
			Sessions.SESSIONS,
			Triggers.TRIGGERS,
			Domains.DOMAINS,
			Constants.CONSTANTS,
			FunctionColumns.FUNCTION_COLUMNS,
			Constraints.CONSTRAINTS,
			CrossReferences.CROSS_REFERENCES,
			InDoubt.IN_DOUBT,
			Views.VIEWS,
			Collations.COLLATIONS,
			ColumnPrivileges.COLUMN_PRIVILEGES,
			TablePrivileges.TABLE_PRIVILEGES,
			Schemata.SCHEMATA,
			FunctionAliases.FUNCTION_ALIASES,
			Rights.RIGHTS,
			Roles.ROLES,
			Users.USERS,
			Sequences.SEQUENCES,
			Help.HELP,
			Settings.SETTINGS,
			Catalogs.CATALOGS,
			TypeInfo.TYPE_INFO,
			TableTypes.TABLE_TYPES,
			Indexes.INDEXES,
			Columns.COLUMNS,
			Tables.TABLES);
	}
}
