/**
 * This class is generated by jOOQ
 */
package org.example.jooq.db.information_schema;


import javax.annotation.Generated;

import org.example.jooq.db.information_schema.tables.Catalogs;
import org.example.jooq.db.information_schema.tables.Collations;
import org.example.jooq.db.information_schema.tables.ColumnPrivileges;
import org.example.jooq.db.information_schema.tables.Columns;
import org.example.jooq.db.information_schema.tables.Constants;
import org.example.jooq.db.information_schema.tables.Constraints;
import org.example.jooq.db.information_schema.tables.CrossReferences;
import org.example.jooq.db.information_schema.tables.Domains;
import org.example.jooq.db.information_schema.tables.FunctionAliases;
import org.example.jooq.db.information_schema.tables.FunctionColumns;
import org.example.jooq.db.information_schema.tables.Help;
import org.example.jooq.db.information_schema.tables.InDoubt;
import org.example.jooq.db.information_schema.tables.Indexes;
import org.example.jooq.db.information_schema.tables.KeyColumnUsage;
import org.example.jooq.db.information_schema.tables.Locks;
import org.example.jooq.db.information_schema.tables.QueryStatistics;
import org.example.jooq.db.information_schema.tables.ReferentialConstraints;
import org.example.jooq.db.information_schema.tables.Rights;
import org.example.jooq.db.information_schema.tables.Roles;
import org.example.jooq.db.information_schema.tables.Schemata;
import org.example.jooq.db.information_schema.tables.Sequences;
import org.example.jooq.db.information_schema.tables.SessionState;
import org.example.jooq.db.information_schema.tables.Sessions;
import org.example.jooq.db.information_schema.tables.Settings;
import org.example.jooq.db.information_schema.tables.Synonyms;
import org.example.jooq.db.information_schema.tables.TableConstraints;
import org.example.jooq.db.information_schema.tables.TablePrivileges;
import org.example.jooq.db.information_schema.tables.TableTypes;
import org.example.jooq.db.information_schema.tables.Triggers;
import org.example.jooq.db.information_schema.tables.TypeInfo;
import org.example.jooq.db.information_schema.tables.Users;
import org.example.jooq.db.information_schema.tables.Views;


/**
 * Convenience access to all tables in INFORMATION_SCHEMA
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
	 */
	public static final ReferentialConstraints REFERENTIAL_CONSTRAINTS = org.example.jooq.db.information_schema.tables.ReferentialConstraints.REFERENTIAL_CONSTRAINTS;

	/**
	 * The table INFORMATION_SCHEMA.KEY_COLUMN_USAGE
	 */
	public static final KeyColumnUsage KEY_COLUMN_USAGE = org.example.jooq.db.information_schema.tables.KeyColumnUsage.KEY_COLUMN_USAGE;

	/**
	 * The table INFORMATION_SCHEMA.TABLE_CONSTRAINTS
	 */
	public static final TableConstraints TABLE_CONSTRAINTS = org.example.jooq.db.information_schema.tables.TableConstraints.TABLE_CONSTRAINTS;

	/**
	 * The table INFORMATION_SCHEMA.SYNONYMS
	 */
	public static final Synonyms SYNONYMS = org.example.jooq.db.information_schema.tables.Synonyms.SYNONYMS;

	/**
	 * The table INFORMATION_SCHEMA.QUERY_STATISTICS
	 */
	public static final QueryStatistics QUERY_STATISTICS = org.example.jooq.db.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

	/**
	 * The table INFORMATION_SCHEMA.SESSION_STATE
	 */
	public static final SessionState SESSION_STATE = org.example.jooq.db.information_schema.tables.SessionState.SESSION_STATE;

	/**
	 * The table INFORMATION_SCHEMA.LOCKS
	 */
	public static final Locks LOCKS = org.example.jooq.db.information_schema.tables.Locks.LOCKS;

	/**
	 * The table INFORMATION_SCHEMA.SESSIONS
	 */
	public static final Sessions SESSIONS = org.example.jooq.db.information_schema.tables.Sessions.SESSIONS;

	/**
	 * The table INFORMATION_SCHEMA.TRIGGERS
	 */
	public static final Triggers TRIGGERS = org.example.jooq.db.information_schema.tables.Triggers.TRIGGERS;

	/**
	 * The table INFORMATION_SCHEMA.DOMAINS
	 */
	public static final Domains DOMAINS = org.example.jooq.db.information_schema.tables.Domains.DOMAINS;

	/**
	 * The table INFORMATION_SCHEMA.CONSTANTS
	 */
	public static final Constants CONSTANTS = org.example.jooq.db.information_schema.tables.Constants.CONSTANTS;

	/**
	 * The table INFORMATION_SCHEMA.FUNCTION_COLUMNS
	 */
	public static final FunctionColumns FUNCTION_COLUMNS = org.example.jooq.db.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

	/**
	 * The table INFORMATION_SCHEMA.CONSTRAINTS
	 */
	public static final Constraints CONSTRAINTS = org.example.jooq.db.information_schema.tables.Constraints.CONSTRAINTS;

	/**
	 * The table INFORMATION_SCHEMA.CROSS_REFERENCES
	 */
	public static final CrossReferences CROSS_REFERENCES = org.example.jooq.db.information_schema.tables.CrossReferences.CROSS_REFERENCES;

	/**
	 * The table INFORMATION_SCHEMA.IN_DOUBT
	 */
	public static final InDoubt IN_DOUBT = org.example.jooq.db.information_schema.tables.InDoubt.IN_DOUBT;

	/**
	 * The table INFORMATION_SCHEMA.VIEWS
	 */
	public static final Views VIEWS = org.example.jooq.db.information_schema.tables.Views.VIEWS;

	/**
	 * The table INFORMATION_SCHEMA.COLLATIONS
	 */
	public static final Collations COLLATIONS = org.example.jooq.db.information_schema.tables.Collations.COLLATIONS;

	/**
	 * The table INFORMATION_SCHEMA.COLUMN_PRIVILEGES
	 */
	public static final ColumnPrivileges COLUMN_PRIVILEGES = org.example.jooq.db.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

	/**
	 * The table INFORMATION_SCHEMA.TABLE_PRIVILEGES
	 */
	public static final TablePrivileges TABLE_PRIVILEGES = org.example.jooq.db.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

	/**
	 * The table INFORMATION_SCHEMA.SCHEMATA
	 */
	public static final Schemata SCHEMATA = org.example.jooq.db.information_schema.tables.Schemata.SCHEMATA;

	/**
	 * The table INFORMATION_SCHEMA.FUNCTION_ALIASES
	 */
	public static final FunctionAliases FUNCTION_ALIASES = org.example.jooq.db.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

	/**
	 * The table INFORMATION_SCHEMA.RIGHTS
	 */
	public static final Rights RIGHTS = org.example.jooq.db.information_schema.tables.Rights.RIGHTS;

	/**
	 * The table INFORMATION_SCHEMA.ROLES
	 */
	public static final Roles ROLES = org.example.jooq.db.information_schema.tables.Roles.ROLES;

	/**
	 * The table INFORMATION_SCHEMA.USERS
	 */
	public static final Users USERS = org.example.jooq.db.information_schema.tables.Users.USERS;

	/**
	 * The table INFORMATION_SCHEMA.SEQUENCES
	 */
	public static final Sequences SEQUENCES = org.example.jooq.db.information_schema.tables.Sequences.SEQUENCES;

	/**
	 * The table INFORMATION_SCHEMA.HELP
	 */
	public static final Help HELP = org.example.jooq.db.information_schema.tables.Help.HELP;

	/**
	 * The table INFORMATION_SCHEMA.SETTINGS
	 */
	public static final Settings SETTINGS = org.example.jooq.db.information_schema.tables.Settings.SETTINGS;

	/**
	 * The table INFORMATION_SCHEMA.CATALOGS
	 */
	public static final Catalogs CATALOGS = org.example.jooq.db.information_schema.tables.Catalogs.CATALOGS;

	/**
	 * The table INFORMATION_SCHEMA.TYPE_INFO
	 */
	public static final TypeInfo TYPE_INFO = org.example.jooq.db.information_schema.tables.TypeInfo.TYPE_INFO;

	/**
	 * The table INFORMATION_SCHEMA.TABLE_TYPES
	 */
	public static final TableTypes TABLE_TYPES = org.example.jooq.db.information_schema.tables.TableTypes.TABLE_TYPES;

	/**
	 * The table INFORMATION_SCHEMA.INDEXES
	 */
	public static final Indexes INDEXES = org.example.jooq.db.information_schema.tables.Indexes.INDEXES;

	/**
	 * The table INFORMATION_SCHEMA.COLUMNS
	 */
	public static final Columns COLUMNS = org.example.jooq.db.information_schema.tables.Columns.COLUMNS;

	/**
	 * The table INFORMATION_SCHEMA.TABLES
	 */
	public static final org.example.jooq.db.information_schema.tables.Tables TABLES = org.example.jooq.db.information_schema.tables.Tables.TABLES;
}
