/**
 * This class is generated by jOOQ
 */
package org.example.jooq.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableTypes implements Serializable {

	private static final long serialVersionUID = -1696402856;

	private String type;

	public TableTypes() {}

	public TableTypes(TableTypes value) {
		this.type = value.type;
	}

	public TableTypes(
		String type
	) {
		this.type = type;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("TableTypes (");

		sb.append(type);

		sb.append(")");
		return sb.toString();
	}
}
